###########################################################################################################
# DO Community Playbooks
# Playbook: Initial Server Setup
# More Info: https://www.digitalocean.com/community/tutorials/automating-initial-server-setup-with-ansible
###########################################################################################################

---
- hosts: all
  remote_user: root
  gather_facts: false
  vars:
    create_user: sammy
    copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Creates a new regular user with sudo privileges
      user:
        name: "{{ create_user }}"
        groups: wheel
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"

    - name: Disables Password Authentication for Root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

- hosts: all
  remote_user: sammy
  become: true
  vars:
    sys_packages: [ 'curl', 'vim', 'git', 'ufw']
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: Install Required System Packages
      apt: name={{ sys_packages }} state=latest

    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming
